export const categoryNames = [
  'Other',
  'Music',
  'Food & Drink',
  'Business',
  'Technology',
  'Health',
  'Sports',
  'Arts',
  'Film & Media',
  'Travel & Outdoor',
  'Charity & Causes',
  'Religion & Spirituality',
  'Education',
  'Holiday',
  'Government',
  'Fashion',
  'Home & Lifestyle',
  'Auto, Boat & Air',
  'Hobbies',
  'School Activities',
  'Community',
];